site:
  title: NARUBench
  description: ""
  keywords: benchmark, cultural understanding, long-form video understanding, multimodal large language models, video question answering
masthead:
  title: 'NARU: A Benchmark for NARrative Evolution and Cultural Nuance Understanding in Japanese Extreme Long Video'
  authors:
    - name: Yuheng Huang
      sup: '*1'
    - name: Jianlang Chen
      sup: '*2'
    - name: Jiayang Song
      sup: "3"
    - name: Hua Qi
      sup: "1"
    - name: Aza Kai
      sup: "4"
    - name: Vincent Markert
      sup: "4"
    - name: Edison Marrese-Taylor
      sup: "1,4"
    - name: Jianjun Zhao
      sup: "2"
    - name: Lei Ma
      sup: 1,5
  author_comment: '* Contributed equally to this work'
  affiliations:
    - The University of Tokyo
    - Kyushu University
    - Macau University of Science and Technology
    - Infinimind Japan Inc.
    - University of Alberta
  links:
    - href: https://arxiv.org/pdf/2608.13210
      icon: fas fa-file-pdf
      label: Paper
    - href: https://arxiv.org/abs/2608.13210
      icon: ai ai-arxiv
      label: arXiv
    - href: https://github.com/infinimind-inc/naru_benchmark
      icon: fab fa-github
      label: Code
    - href: https://huggingface.co/datasets/infinimind/naru_benchmark
      icon: far fa-images
      label: Data
footer:
  paperPdf: https://arxiv.org/pdf/2608.13210
  github: https://github.com/infinimind-inc/naru_benchmark
